use std::time::{SystemTime, UNIX_EPOCH};

use axum::http::HeaderValue;
use rand::RngCore;
use sha2::{Digest, Sha256};

/// Name of the bookkeeping file kept inside each compile directory.
pub const MANIFEST_NAME: &str = ".underleaf-manifest";

pub fn now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

pub fn now_ms() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0)
}

pub fn random_hex(bytes: usize) -> String {
    let mut b = vec![0u8; bytes];
    rand::thread_rng().fill_bytes(&mut b);
    hex::encode(b)
}

pub fn new_id() -> String {
    random_hex(12)
}

pub fn sha256_hex(data: &[u8]) -> String {
    hex::encode(Sha256::digest(data))
}

/// IDs generated by us are lowercase hex. Validating them early keeps path
/// parameters from ever reaching the filesystem in an unexpected shape.
pub fn is_valid_id(s: &str) -> bool {
    !s.is_empty() && s.len() <= 64 && s.bytes().all(|b| b.is_ascii_hexdigit())
}

/// A valid file or folder name (single path component).
pub fn valid_name(n: &str) -> bool {
    !n.is_empty()
        && n.len() <= 200
        && n != "."
        && n != ".."
        && n != MANIFEST_NAME
        && n.trim() == n
        && !n.chars().any(|c| c == '/' || c == '\\' || c.is_control())
}

pub fn normalize_newlines(s: String) -> String {
    let s = match s.strip_prefix('\u{feff}') {
        Some(rest) => rest.to_string(),
        None => s,
    };
    if s.contains('\r') {
        s.replace("\r\n", "\n").replace('\r', "\n")
    } else {
        s
    }
}

pub fn extension(name: &str) -> String {
    match name.rsplit_once('.') {
        Some((stem, ext)) if !stem.is_empty() => ext.to_ascii_lowercase(),
        _ => String::new(),
    }
}

/// Escape a plain string for use inside LaTeX source.
pub fn latex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\textbackslash{}"),
            '&' | '%' | '$' | '#' | '_' | '{' | '}' => {
                out.push('\\');
                out.push(c);
            }
            '~' => out.push_str("\\textasciitilde{}"),
            '^' => out.push_str("\\textasciicircum{}"),
            _ => out.push(c),
        }
    }
    out
}

pub fn content_disposition(kind: &str, filename: &str) -> HeaderValue {
    let ascii: String = filename
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || "._- ()".contains(c) {
                c
            } else {
                '_'
            }
        })
        .collect();
    let mut enc = String::with_capacity(filename.len() * 3);
    for b in filename.bytes() {
        if b.is_ascii_alphanumeric() || b == b'.' || b == b'_' || b == b'-' {
            enc.push(b as char);
        } else {
            enc.push_str(&format!("%{b:02X}"));
        }
    }
    HeaderValue::from_str(&format!(
        "{kind}; filename=\"{ascii}\"; filename*=UTF-8''{enc}"
    ))
    .unwrap_or_else(|_| HeaderValue::from_static("attachment"))
}

/// Return at most `max` bytes from the end of `s`, cut on a char boundary.
pub fn tail(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_string();
    }
    let mut start = s.len() - max;
    while start < s.len() && !s.is_char_boundary(start) {
        start += 1;
    }
    format!("[... truncated ...]\n{}", &s[start..])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names() {
        assert!(valid_name("main.tex"));
        assert!(!valid_name("../x"));
        assert!(!valid_name("a/b"));
        assert!(!valid_name(""));
        assert!(!valid_name(" x"));
    }

    #[test]
    fn escape() {
        assert_eq!(latex_escape("a_b & 50%"), "a\\_b \\& 50\\%");
    }

    #[test]
    fn ext() {
        assert_eq!(extension("Main.TeX"), "tex");
        assert_eq!(extension(".latexmkrc"), "");
        assert_eq!(extension("Makefile"), "");
    }
}
